

services:
  streamlit:
    build:
      context: ..
      dockerfile: app/Dockerfile.app
    container_name: streamlit-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    # Mount only the DB handler for live development (optional) and ensure imports work
    volumes:
      - ../src/utils/db:/app/src/utils/db:ro
    environment:
      - PYTHONPATH=/app